import type { Metadata } from "next";
import * as React from 'react';
import { CssBaseline } from '@mui/material';
import dynamic from 'next/dynamic';

const About = dynamic(() => import('./Components/About'))
const Drawer = dynamic(() => import('./Components/DrawerAppBar'))

export const metadata: Metadata = {
  title: "Portafolio",
  description: "Generated by Miguel Plasencia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CssBaseline />
      <body style={{
           margin: 0,
           padding: 0,
           width: "100%",
           height: "100vh", // Añadido para asegurar que ocupe toda la pantalla
           display: "flex",  // Para usar flexbox
           flexDirection: "column", // Apilar el contenido (navbar, main, footer)
           backgroundColor: '#0F1214'
        }}>
        {/* Navbar */}
        <Drawer/>
        {/* Contenido */}
        <main>
          {children}
          <About/>
        </main>

        {/* footer */}
        <footer>

        </footer>
      </body>
    </html>
  );
}
