import type { Metadata } from "next";
import * as React from 'react';
import { CssBaseline } from '@mui/material';


export const metadata: Metadata = {
  title: "Portafolio",
  description: "Generated by Miguel Plasencia",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CssBaseline />
      <body style={{
           margin: 0,
           padding: 0,
           width: "100%",
           height: "100vh", // Añadido para asegurar que ocupe toda la pantalla
           display: "flex",  // Para usar flexbox
           flexDirection: "column", // Apilar el contenido (navbar, main, footer)
           backgroundColor: '#444444'
        }}>
        {/* Navbar */}
        
        {/* Contenido */}
        <main>
          {children}
        </main>

        {/* footer */}
        <footer>

        </footer>
      </body>
    </html>
  );
}
