import type { Metadata } from "next";
import * as React from 'react';
import { CssBaseline } from '@mui/material';
import PropTypes from 'prop-types';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Divider from '@mui/material/Divider';
import Drawer from '@mui/material/Drawer';
import IconButton from '@mui/material/IconButton';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemText from '@mui/material/ListItemText';
import MenuIcon from '@mui/icons-material/Menu';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import dynamic from 'next/dynamic';

const About = dynamic(() => import('./Components/About'))

const drawerWidth = 240;
const navItems = ['Home', 'About', 'Contact'];


export const metadata: Metadata = {
  title: "Portafolio",
  description: "Generated by Miguel Plasencia",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CssBaseline />
      <body style={{
           margin: 0,
           padding: 0,
           width: "100%",
           height: "100vh", // Añadido para asegurar que ocupe toda la pantalla
           display: "flex",  // Para usar flexbox
           flexDirection: "column", // Apilar el contenido (navbar, main, footer)
           backgroundColor: '#0F1214'
        }}>
        {/* Navbar */}
        
        {/* Contenido */}
        <main>
          {children}
          <About/>
        </main>

        {/* footer */}
        <footer>

        </footer>
      </body>
    </html>
  );
}
